apiVersion: cinder.openstack.org/v1beta1
kind: Cinder
metadata:
  name: cinder
  namespace: openstack
spec:
  serviceUser: cinder
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseUser: cinder
  cinderAPIReplicas: 1
  cinderSchedulerReplicas: 1
  cinderBackupReplicas: 1
  cinderBackupNodeSelectorRoleName: worker
  secret: cinder-secret
  cinderAPIContainerImage: docker.io/tripleomaster/centos-binary-cinder-api:current-tripleo
  cinderSchedulerContainerImage: docker.io/tripleomaster/centos-binary-cinder-scheduler:current-tripleo
  cinderBackupContainerImage: docker.io/tripleomaster/centos-binary-cinder-backup:current-tripleo
  cinderVolumes:
  - name: volume1
    containerImage: docker.io/tripleomaster/centos-binary-cinder-volume:current-tripleo
    replicas: 1
    nodeSelectorRoleName: worker
